### ISSUE TITLE
Antlr Parser/Lexer conflict with negative numbers

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#186] opened 2022-02-08 17:32 UTC
In GitLab by @DerSchmidt on Feb 8, 2022, 18:32

The Antlr Lexer for DaphneDSL and SQL sometimes consumes too many characters. 
An Example for this behavior is:

`
print(1 -2); print(1-2);
`

The missing space between '-' and '2' leads to the Lexer consuming both characters and creating the '-2' token. This leads to a Parser error. 

_Parsetree:_ (script (statement (exprStatement (expr print ( (expr (literal 1)) -2 )) ;)) <EOF>)

`
print(1 - 2); print(1- 2);
`

The extra space in between '-' and '2' prevents the Lexer to make a '-2' token.

_Parsetree:_ (script (statement (exprStatement (expr print ( (expr (expr (literal 1)) - (expr (literal 2))) )) ;)) <EOF>)

**Comment by pdamme** [comment] 2023-07-18 15:53
This issue is related to (or a duplicate of) #560.

**Closed** 2024-07-02 17:48 UTC
Labels: bug
