### ISSUE TITLE
Possible bug: now() multiplied by f32 and cast into f64 produces error

### ISSUE THREAD

**Issue by divjakm** [daphne-eu/daphne#542] opened 2023-06-08 15:14 UTC
Hello, hello!

While playing with DaphneDSL scripts I noticed a weird behavior (possibly a bug) when using the output of **now()** function. If I multiply it's output by a f32 value and then try to cast the result into f64, I get an error:

![daphne_bug01](https://github.com/daphne-eu/daphne/assets/135989443/ee7bf195-e916-4fa1-ab64-f9d87a54a42d)

If I do the same operations with manually created f32/f64 values it works as it should. I tested this in old release version as well as the new release candidate for v0.2. Here is the code to replicate this:

// this works:
t = as.f32(10);
tt = as.f64(t);

// this works:
t = as.f32(10) * as.f32(20);	// f32 * f32 works, f32 * f64 works
tt = as.f64(t);

// this works:
t = now();
tt = as.f64(t);

// this works:
t = now() * as.f64(20);	// f32 * f64 works
tt = as.f64(t);

// this DOESN'T WORK:
t = now() * as.f32(20);	// f32 * f32 doesn't work
tt = as.f64(t);			// throws error

**Comment by pdamme** [comment] 2023-06-08 20:11
Thanks for reporting this bug, @divjakm. I can reproduce it.

The error message indicates that there is no pre-compiled instantiation of the `cast`-kernel for argument type `float`/`f32` and result type `double`/`f64`. I know this error message looks a bit cryptic, but at least it's [documented](https://github.com/daphne-eu/daphne/blob/main/doc/RunningDaphneLocally.md#jit-session-error-symbols-not-found-). The problem can be fixed by adding an appropriate instantiation of the `castSca`-kernel in `src/runtime/local/kernels/kernels.json`, and I'm about to commit such a fix.

-----

*Background:* The reason why it happened with `now()`, but not in the other cases above is that the DAPHNE compiler optimizes away `cast`s of scalars known at compile-time (such as the literals you hard-coded in your examples). If you're interested, you can check this using DAPHNE's `--explain` feature:

- DaphneDSL script (say, `my-example.daphne`):
  ```
  t = as.f32(10);
  tt = as.f64(t);
  print(tt);
  ```
- Explain IR right after parsing (no simplifcations yet):
  ```
  bin/daphne --explain parsing my-example.daphne
  ```
  ```
  IR after parsing:
  module {
    func.func @main() {
      %0 = "daphne.constant"() {value = 10 : si64} : () -> si64
      %1 = "daphne.constant"() {value = 10 : si64} : () -> si64
      %2 = "daphne.cast"(%1) : (si64) -> f32
      %3 = "daphne.cast"(%2) : (f32) -> f64
      %4 = "daphne.constant"() {value = true} : () -> i1
      %5 = "daphne.constant"() {value = false} : () -> i1
      "daphne.print"(%3, %4, %5) : (f64, i1, i1) -> ()
      "daphne.return"() : () -> ()
    }
  }
  10
  ```
  The `costant` is of type `si64` and there is a `cast` from `si64` to `f32` and a `cast` from `f32` to `f64`.
- Explain IR after some simplifcations:
  ```
  bin/daphne --explain parsing_simplified my-example.daphne
  ```
  ```
  IR after parsing and some simplifications:
  module {
    func.func @main() {
      %0 = "daphne.constant"() {value = 1.000000e+01 : f64} : () -> f64
      %1 = "daphne.constant"() {value = false} : () -> i1
      %2 = "daphne.constant"() {value = true} : () -> i1
      "daphne.print"(%0, %2, %1) : (f64, i1, i1) -> ()
      "daphne.return"() : () -> ()
    }
  }
  10
  ```
  Now the constant is of type `f64` and all `cast`s have been resolved at compile-time to simplify the program. That means the missing kernel instantiation will never be requested. As `now()` is not compile-time constant, such optimizations don't apply.

**Closed** 2023-06-08 20:16 UTC
Labels: bug
