### ISSUE TITLE
DaphneDSL: Function to determine the type of an object

### ISSUE THREAD

**Issue by RetoKrummenacher** [daphne-eu/daphne#357] opened 2022-05-06 22:00 UTC
Similar to R's typeof(), it would be nice to have a function to check the object type in DaphneDSL. The output can be a pure string, meaning it is a feature to get information and not to be used in casting operations.

Some possible examples could be:
```
f = 5.0;
typeof(f); # --> f64 
d = reshape(seq(1.0,5.0,1.0),5,1);
typeof(d1); # --> matrix double
i = reshape(seq(1,5,1),1,5);
typeof(i); # --> matrix int64
```

This is useful when working with type casting. As printing alone does not provide enough information.

**Comment by pdamme** [comment] 2022-05-12 20:52
I agree, this would be a useful feature, especially while debugging DaphneDSL scripts. We will implement it.

**Comment by pdamme** [comment] 2023-03-28 22:50
This is actually an interesting "good first issue", which provides an opportunity to take a tour through various layers of the system. Here are a few suggestions on addressing it.

Ultimately, we want a DaphneDSL built-in function `typeof`, which returns the data/value type of its single argument as a string. I propose it should return the physical data type (e.g., `DenseMatrix`/`CSRMatrix`) instead of the logical data type (e.g., `matrix`), since that will be more useful for debugging. A few examples for possible outputs: `f64`, `si32`, `str`, `DenseMatrix<f64>`, `CSRMatrix<ui8>`, `Frame<si32, f64, ui8>`.

**Some hints on required changes:**
- *DaphneIR*
  - A new DaphneIR operation (see `src/ir/daphneir/DaphneOps.td`), say `TypeOfOp`, which gets a value of any matrix, frame, or scalar type as input, and yields a string as output.
- *DaphneDSL*
  - A new built-in function, say `typeof` in DaphneDSL (see `src/parser/daphnedsl/DaphneDSLBuiltins.cpp`), which produces a `TypeOfOp` in the IR.
- *Runtime*
  - A new kernel for `TypeOfOp` in `src/runtime/local/kernels/`. See the developer documentation on implementing a new kernel in `doc/development/ImplementBuiltinKernel.md`. We need a kernel-struct, a convenience function, and specializations for all possible data/value types.
  - To concisely handle the combinations of data and value types, the specializations for `DenseMatrix`, `CSRMatrix`, and `Frame` could call those for the scalar types to get the string representation of their value/column type(s).
  - Note that for `DenseMatrix` and `CSRMatrix`, the value type is a template parameter, while for `Frame`, the value types of the columns must be interpreted at runtime (see `src/runtime/local/datastructures/Frame.h`::`getColumnType()`).
  - Furthermore, the new kernel must be registered in `src/runtime/local/kernels/kernels.json` (with instantiations for all data/value types); these are the variants which get precompiled and are then available from DaphneDSL.
  - Existing kernels can serve as a blueprint. For instance, `concat` (`src/runtime/local/kernels/Concat.h`) also returns a string.

**Moreover, it would be great to:**
- Add some test cases. I think script-level test cases are most useful here. They can be found in `test/api/cli/`. The basic idea is to provide pairs of a DaphneDSL script and a plain text file with the expected output. A cpp-file is needed which invokes the necessary test helper functions like `compareDaphneToRef()`, but there are numerous examples in the existing script-level test cases. Unit test cases, which directly call the kernel in C++ could also be added (but that's not as important in this case, IMHO). They reside in `test/runtime/local/kernels/`.
- Update the documentation (DaphneDSL built-in functions).

**Comment by pdamme** [comment] 2024-05-23 21:02
Search for `(see #357)` in the code base for some spots where the `typeof()` function could be directly useful.

**Comment by Garic152** [comment] 2024-06-12 06:08
Could you please assign this issue to me?

**Comment by pdamme** [comment] 2024-06-12 10:26
Sure, go ahead!

**Comment by Garic152** [comment] 2024-06-14 07:10
I started implementing the typeof kernel for scalars only first before adding support for other data types, but unfortunately, I can't seem to resolve a mistake in my typeof.h code.

[Recent branch which fails](https://github.com/Garic152/daphne/tree/dev-issue-357)

More specifically, the compiler doesn't seem to like the way i call `void typeof(char *& res, const DTArg * arg, DCTX(ctx))`.

As the Issue description requested, the function should return a string, so I implemented the kernel template as follows:

```json
    {
        "kernelTemplate": {
            "header": "TypeOf.h",
            "opName": "typeof",
            "returnType": "void",
            "templateParams": [
                {
                    "name": "DTArg",
                    "isDataType": true
                }
            ],
            "runtimeParams": [
                {
                    "type": "char *&",
                    "name": "res"
                },
                {
                    "type": "const DTArg *",
                    "name": "arg"
                }
            ]
        },
        "instantiations": [
            ["size_t"],
            ["double"],
            ["float"],
            ["int64_t"],
            ["int32_t"],
            ["int8_t"],
            ["uint64_t"],
            ["uint32_t"],
            ["uint8_t"],
            ["bool"]
        ]
    },
```
As of my understanding, this "initializes" the typeof function with a variable argument and a result char/string, which has to be taken as an input by the template functions and then get depending on the datatype in `typeof.h`.

I've tried adjusting all the other files correlated to the typeof kernel, but always get a similar error message to this: [Error Message Gist](https://gist.github.com/Garic152/d6410e2e14341a4c08952b4c5f86cf58)

This is probably quite a trivial mistake on my end but I would really appreciate a small pointer to my mistake to avoid wasting any more time on this error and continue implementing the Matrices/Frames as well.

**Comment by pdamme** [comment] 2024-06-14 20:41
Hi @Garic152, at a quick glance, the way you specify the result type looks good to me (and is consistent with, e.g., the `concat`-kernel). I think the problem is that the C++ compiler gets confused by the name of the kernel's convenience function, as `typeof` (all lower case) is an operator in C. Try renaming the function to `typeOf` (upper-case `O`) (in `TypeOf.h` and `kernels.json`) (that would also be more consistent with the CamelCasing in the kernel struct name).

**Comment by Garic152** [comment] 2024-06-21 08:46
After some refactoring of the TypeOf scalar function, everything should work fine now and my commits have been pushed.

For script-level testing, I initially thought about including the TypeOf test in an existing test file. 
After noticing that creating a rand() matrix with sparsity set to 0.0 does not make the compiler treat it as a sparse matrix, I created a new TypeOfTest.cpp file to not change the structure of the existing test files too much.
The new test file uses a second test case with the `--set-matrix-repr=1` command-line argument to handle both dense and sparse matrices.
The sparse matrix test only tests for si64 and f64 as the other datatypes were not supported, please let me know if I misread something there.

**Closed** 2024-09-02 12:14 UTC
Labels: good first issue
